version: '3'

services:
  borg:
    image: zokradonh/borgbackup-docker
    restart: unless-stopped
    volumes:
      - /var/lib/docker/volumes:/hostvolumes
      - /var/run/docker.sock:/var/run/docker.sock
      - config:/borgconfig
      - backups:/backups

volumes:
  backups:
    labels:
      - xyz.zok.borgbackup.ignore
  config:
    labels:
      - xyz.zok.borgbackup.ignore
